server/persistence/bolt/bolt.go
This seems to have been left in from a long time ago!
=> Remove unnecessary println

server/listeners/mock.go, server/listeners/tcp.go, server/listeners/websocket.go
But I'm not sure if this is possible in check origin, I mean elegant
https://github.com/ClarkQAQ/mqtt/commit/b9db59ba121d4fe8ea24babe9fc9cf581f0a51be
=> Fixed some bugs, wish the project better and better

examples/redis/main.go, server/internal/topics/trie.go, server/persistence/redis/redis.go, server/persistence/redis/redis_test.go, server/server.go
1. Added redis persistence mode
2. Added redis persistence example
3. Fixed cannot replace old retained message bug
4. Fixed type assignment bug when persistent inflight message
=> added redis persistence mode

server/events/events.go, server/server.go
This PR adds new events to also get notified if a subscription is created or removed.
=> Add topic un-/subscribe events

server/events/events.go, server/internal/packets/codec_test.go, server/internal/packets/packets.go
A few clean ups to make the linter happy
=> Goreport fixes

listeners/websocket.go
Hi @mochi-co 👋🏻  Today I've spent some time with a colleague @svanharmelen, trying to understand the problem and search for the root cause.
We concluded that the problem is not with the client, as we tried to send the same amount of messages to Mosquitto (and also increased the test to 100.000 messages) which didn't give us any issues.
Next we looked at the websocket package that is used in your package and to rule things out we swapped it out for https://godoc.org/nhooyr.io/websocket. Funny enough this solved the issue, but as we were not convinced it's a bug in the Gorilla package and we didn't understand the root cause yet, we continued our search in `listeners/websocket.go`.
In there, we noticed in the [Read](https://github.com/mochi-co/mqtt/blob/master/listeners/websocket.go#L140) …
=> Fix websocket malformed packet bug

listeners/unixsock.go, listeners/unixsock_test.go
To improve process communication performance
=> Add unix socket listener

clients.go, clients_test.go
Add a Closed method to Client, returns true if client connection is closed.
=> Add Client Closed

hooks/storage/badger/badger.go, hooks/storage/bolt/bolt.go, hooks/storage/redis/redis.go
Otherwise the subscription properties will be lost during recovery.
=> Save subscription properties for mqttv5

server.go
Change the order of inline client check to improve direct publish performance and avoid potential errors from custom ACLCheck.
=> Change the order of inline client check

hooks.go
As identified by @thedevop in #135, this change makes the hooks slice safe for concurrent usage.
=> Make hooks safe for concurrency

server.go, server_test.go
Alternative to #143 / #144
- Ensure retained messages on inherited subscriptions are only published following the Connack packet.
=> Publish retained messages only after connack

hooks/storage/storage_test.go, server.go, system/system.go, system/system_test.go
Feel free to change the metrics name. Also, I didn't add this to publishSysTopics as I'm not sure what topics you want to use.
=> Add PublishDropped metrics

topics.go
=> Common subscriptions issued by different clients at the same time may be lost

clients.go, server.go
=> Ensure to close client WriteLoop

README.md, hooks.go, hooks_test.go
Adds a new OnPacketIDExhausted hook per #201
=> Add OnPacketIDExhausted hook

examples/tls/main.go
Update the example file to avoid confusion for future users
=> Fix example usage of NewHTTPStats

hooks.go, hooks_test.go, server.go
Add OnRetainPublished hook, it is called when a retained message is published.
=> Add OnRetainPublished hook

topics.go, topics_test.go
Bug fix for subscriber of a/b receiving messages for a/b/c... as discovered by @x20080406 in #239.
=> Fix ScanSubscribersTopicInheritanceBug

hooks/auth/ledger.go
Fixes issue #258 in which the filters for the ledger ACL rules were selected at random due to the behaviour of the `range` operator. This PR changes the order of operations to first check for Write access filters, then Read filters, and finally Deny filters.
It's slightly less optimised than it could be, but it should be fixed first, and optimised later if anyone feels the need to do so.
=> Preference Write, Read, Deny filters in ledger

hooks/storage/badger/badger.go
Potential fix for https://github.com/mochi-co/mqtt/issues/265
=> fix: data-race in badger hook

server.go
As issue #286, I do some change in server.publishToClient
=> add aclcheck in publishToClient

clients.go, server_test.go
Reverts mochi-mqtt/server#321 until a consensus is made in #322
=> Revert "improve transport performance with bufio"

examples/hooks/main.go
In issues #332  and #330 , users raised the same question about how to use subscribe and publish directly within a hook. Therefore, I added a demonstration in examples/hooks on how to achieve this.
=> Demo how to subscribe and publish directly within examples/hooks.
