mochi-mqtt/server

- .gitignore
- README.md
- examples/events/main.go
- server/internal/circ/writer.go
- server/internal/clients/clients.go
- server/listeners/tcp.go
- server/server.go
- server/server_test.go
Adds the ability to directly publish messages from the embedding service using the `func (s *Server) Publish(topic string, payload []byte, retain bool) error` method.
Also provides various commentary cleanups for clarity.
> Inline Publishing

- .gitignore
- README.md
- examples/events/main.go
- server/events/events.go
- server/server.go
- server/server_test.go
Adds OnConnect and OnDisconnect Event hooks, allowing embedding services to gain information about the connection and disconnection of clients.
> OnConnect and OnDisconnect Event Hooks

- server/internal/circ/buffer.go
- server/internal/circ/buffer_test.go
- server/internal/circ/reader.go
- server/internal/circ/reader_test.go
- server/internal/circ/writer.go
- server/internal/circ/writer_test.go
- server/internal/clients/clients.go
- server/internal/clients/clients_test.go
- server/internal/packets/fixedheader.go
- server/internal/packets/fixedheader_test.go
- server/listeners/http_sysinfo.go
- server/listeners/tcp.go
- server/listeners/websocket.go
- server/server.go
- server/system/system_test.go
This is mainly a fix for #17, where 64-bit variables may be misaligned for atomic operations on 32-bit systems. I think I found all struct fields that are used in atomic operations. Those that are used as simple flags are changed to `uint32` so they'll be aligned correctly on all systems. Some fields are used for counting things, so I assumed they might really need more than 32 bits. For those, I added tests that will check that alignment requirements are meet even when the tests run on 64-bit systems.
While investigating the atomic operations, I noticed a race condition between atomic loads and stores, and fixed it with a compare-and-swap operation.
Finally, the test for `encodeLength` assumed that `int` and `int64` always have the same range. I had to change the function signature to …
> Improve 32-bit compatibility

- server/internal/circ/buffer.go
- server/internal/circ/buffer_test.go
- server/internal/circ/reader.go
- server/internal/circ/reader_test.go
- server/internal/circ/writer.go
- server/internal/circ/writer_test.go
- server/internal/clients/clients.go
- server/internal/clients/clients_test.go
- server/internal/packets/fixedheader.go
- server/internal/packets/fixedheader_test.go
- server/listeners/http_sysinfo.go
- server/listeners/tcp.go
- server/listeners/websocket.go
- server/server.go
- server/system/system_test.go
Issue #17 demonstrated that the broker could not be run on ARM32 due to invalid memory address errors. This is due to the use of unaligned int64s. This PR corrects the alignment of structs using atomic int64s. Additionally, where it makes sense to do so, int64 fields have been converted to uint32 fields.
- Passes Paho interoperability tests
- Passes all unit tests
> ARM32 Compatibility

- server/internal/circ/buffer.go
- server/internal/circ/pool.go
- server/internal/circ/pool_test.go
- server/internal/circ/reader.go
- server/internal/circ/writer.go
- server/internal/circ/writer_test.go
- server/internal/clients/clients.go
- server/internal/packets/fixedheader.go
- server/internal/packets/fixedheader_test.go
- server/internal/packets/packets.go
- server/internal/topics/trie.go
- server/listeners/http_sysinfo.go
- server/listeners/listeners.go
- server/listeners/mock.go
- server/listeners/tcp.go
- server/listeners/websocket.go
- server/persistence/persistence.go
- server/server.go
- server/server_test.go
In v1.1.0 we made changes to the alignment of several structs (particularly `Buffer`) in order to ensure the broker is compatible with 32bit systems. In the process we discovered that other structs were not aligned in an optimised manner. This PR aligns all structs to 8bit boundaries and ensures they are packed most efficiently.
This PR also contains other minor fixes:
- Locks were being copied in the `Inflight`, `Buffer` structs. These are now passed by address where appropriate.
- The method signature for `writer WriteTo` implemented an `int` instead of `int64`. This has been corrected and references to the method updated.
- Small changes to comments for clarity.
Tested on 32 and 64 bit platforms:
- Paho interoperability tests pass.
- Multiple iterations of inovex mqtt-stresser succeed …
> Optimise Struct Fields + Fixes

- README.md
- server/internal/packets/codec.go
- server/internal/packets/codec_test.go
- server/internal/packets/packets.go
- server/server.go
**What are you trying to achieve?**
I'm testing this MQTT broker service with the use of Sparkplug-B payloads. The payloads are Google protobuf encoded, are not and should not be expected to be valid UTF8. The is-valid-UTF8 test was causing my device's connection to fail during setup because the Will Message was invalid protobuf data.
The MQTT specification does not require UTF8 for []byte payloads, only for certain string fields, as I understand it.
Note: While testing, I discovered that ErrOffsetBytesOutOfRange was not being used. The `decodeBytes()` method was returning the error for string decoding. I have updated/improved the tests of the decode methods to test for expected errors explicitly and added an invalid-UTF8 test case.
**Why are you doing this?**
Correcting the use of errors …
> Support non-UTF8 payloads (per MQTT specification)

- README.md
- examples/redis/main.go
- server/persistence/redis/redis.go
- server/persistence/redis/redis_test.go
- server/server.go
With redis as the datastore, services can be separated from storage, services can be redeployed to any machine, and data can be recovered。
> Add redis persistence mode and example

- server/internal/clients/clients.go
Fixes most of #25. Extracted from #34.
The one (and only) test failure that I still see after this fix, also mentioned in #25, is:
```
--- FAIL: TestServerResendClientInflightBackoff (0.00s)
server_test.go:2109: 
Error Trace:	server_test.go:2109
Error:      	Not equal: 
expected: 1
actual  : 2
Test:       	TestServerResendClientInflightBackoff
```
> Move two WaitGroup.Add calls

- server/internal/packets/packets.go
- server/internal/packets/packets_tables_test.go
- server/internal/packets/packets_test.go
Follow up from https://github.com/mochi-co/mqtt/pull/29#issuecomment-1053365833
> Wrap packet errors with cause information

- server/events/events.go
- server/internal/circ/reader.go
- server/internal/circ/reader_test.go
- server/internal/clients/clients.go
- server/internal/clients/clients_test.go
- server/listeners/tcp.go
- server/server.go
- server/server_test.go
Redo of #34.
Fixes #33.
Fixes #21.
Incorporates #36. 
Adds an OnError handler for errors that are not reported via the OnDisconnect handler.
Results from auditing error propagation in the server.
- an error was being skipped from ResendInflight
- an error was being ignored in `Reader.ReadFrom()`, which wasn't causing harm but made diagnosing other issues (and test coverage) more difficult
Adds a "Session reestablished" error to indicate when one client connection causes another to disconnect. For example, when two clients use the same ID, the server logs might read:
```
<< OnConnect client connected operator from [::1]:56779
<< OnDisconnect client disconnected operator connection from [::1]:56779: Session reestablished
```
Extends a few existing tests to hit test coverage.  Extensive …
>  Add an OnError handler, report the reason for disconnects

- server/internal/packets/packets.go
- server/internal/packets/packets_test.go
- server/server.go
- server/server_test.go
This combines:
1. Uses of `strconv.Itoa(int(x))` replaced with `strconv.FormatInt()` or `strconv.FormatUint()`
2. Tests that read values set by `atomic.StoreInt64()` use atomic reads as well.
The first would be needed to show system counters correctly on a 32-bit platform.
The second is part of #25 required to pass tests with `-race`.
> Two no-functional-change cleanups combined

- Dockerfile
This PR adds a very basic Dockerfile base on Alpine and Go 1.18
To use it, first 
```
docker build -t mochi:latest .
```
Then to run it with TCP, Websocket, and also HTTP dashboard available on the host:
```
docker run -p 1883:1883 -p 1882:1882 -p 8080:8080 mochi:latest
```
> docker: add initial simple Dockerfile

- server/events/events.go
- server/server.go
- server/server_test.go
This event gets called right after ACL checking but before any other
Fields of the packet get evaluated.
Closes #44
> Events: Add OnProcessMessage event

- server/server.go
As per #59 - in two places in `server.go`, the `persistence.KRetained` key was used when it should be the `persistence.KInflight` key.
This PR resolves #59.
> Fix Inflight Persistence Key

- README.md
- server/events/events.go
- server/server.go
- server/server_test.go
As per our discussions in https://github.com/mochi-co/mqtt/pull/53#pullrequestreview-917410043, this pull request adds the ability to Reject a packet from the `onProcessMessage` event hook. 
- Adds the ErrRejectPacket error. When returned from an `onProcessMessage` callback, the packet processing will be abandoned.
- Add optional error logging for `OnProcessMessage` using the `OnError` event, if one is set.
- Updates tests to ensure rejected packets are properly abandoned.
- Updates Readme and Events documentation to describe the usage of ErrRejectPacket.
FAQ @jmacd, @stffabi
> Add ErrRejectPacket to OnProcessMessage

- README.md
- cmd/main.go
- examples/dashboard/main.go
- examples/events/main.go
- examples/persistence/main.go
- examples/tcp/main.go
- examples/tls/main.go
- examples/websocket/main.go
- server/internal/circ/pool.go
- server/server.go
- server/server_test.go
As per our discussion on issue #54, this pull request provides the ability to pass a struct of server options to the new server in order to override certain configuration values. In particular, it allows the operator to increase (or decrease) the size of the buffer and block used in the circular buffer for each client. This is necessary in systems where larger message payloads would otherwise be dropped due to over-running the buffer.
Key changes:
- A new `NewServer(opts *Options) *Server` function has been added to `server.go`, which allows the instantiation of a server with options. The original `New() *Server` function should be deprecated.
- __Discussion:__ Alternatively, A) we introduce a breaking change and add the `opts *Options` parameter directly to the existing `New` function. …
> Configurable Server Options

- server/internal/circ/pool.go
- server/internal/circ/pool_test.go
- server/internal/clients/clients.go
- server/internal/clients/clients_test.go
- server/persistence/bolt/bolt.go
- server/server.go
- server/server_test.go
This PR resolves #52 and the [conversation contained within](https://github.com/mochi-co/mqtt/pull/52#discussion_r830854647), in which it was determined that in some cases, the `xbr` and `xbw` client buffers could be leaked because the pool blocks were neither being returned to the pool. This occurred in any scenario where the client did not cleanly disconnect. Furthermore nor were the client's `r` and `w` buffers were not being released when a client disconnected, preventing the garbage collector from freeing up the buffer space for each client. 
Specifically:
- The `EstablishConnection` method has been rebuilt. Where the buffers were previously released by direct calls, defer statements are now used.
- Where connection failures were handled by a single ack response, multiple logic …
> Release client buffers

- server/internal/topics/trie.go
- server/internal/topics/trie_test.go
- server/server.go
Resolves issue #43 in which only the first retained messages would be stored. This was caused by the incorrect evaluation of the returned r-value which indicated whether or not the message had been persisted. Simplifying the logic for returning this value fixes the issue in persistent stores.
> Fix Store Retained Messages

- examples/tls/main.go
- server/listeners/http_sysinfo.go
- server/listeners/http_sysinfo_test.go
- server/listeners/listeners.go
- server/listeners/listeners_test.go
- server/listeners/tcp.go
- server/listeners/tcp_test.go
- server/listeners/websocket.go
- server/listeners/websocket_test.go
This PR deprecates the Listener `config.TLS` value and instead exposes a new field, `config.TLSConfig` which takes a `*tls.Config` value.
Previously the setting of TLS certificates was handled by the broker, using `config.TLS`. However, this is a limiting approach, as it prevents users from configuring the TLS as they wish. Instead, the `config.TLS` field is deprecated, and we expose a new field, `config.TLSConfig`, which takes the `*tls.Config` value directly. 
This change allows users to set their own CA Cert Pool for client authentication, as requested in #79
> Expose tls.Config to Listeners

- examples/tcp/main.go
- server/internal/clients/clients.go
- server/internal/clients/clients_test.go
- server/persistence/bolt/bolt.go
- server/persistence/bolt/bolt_test.go
- server/persistence/persistence.go
- server/persistence/persistence_test.go
- server/server.go
- server/server_test.go
- Previously, inflight messages were only resent when a client with the same ID reconnected without a clean-session. A new case has been added to the server event loop to periodically attempt resending pending inflight messages to connected clients, dropping them after the maximum number of resends (only if the client is connected, so not affecting message queuing).
- To prevent queued QOS messages from accumulating for clients who have not reconnected, a TTL feature has been added allowing queued inflight messages to be cleared after a set duration (default 24 hours).
- The Persistence interface has been updated to provide a method for clearing expired inflight messages in layers which do not support native TTL solutions (bolt), and a setInflightTTL method has been added to propagate the …
> Adds Inflight TTL and Period Resend

- server/internal/clients/clients.go
- server/internal/clients/clients_test.go
- server/server.go
As per #98 and #96 - a data race was occurring when the primary server routine and client routines attempted to access the client inflight messages map at the same time, causing fatal errors.
The issue was reproduced placing the server under heavy load with inovex/mqtt-stresser, using qos=2 for both the publisher and subscriber (see #98). 
This PR fixes the issue by returning reference maps of the original values, values in the case of inflight messages, pointers to clients in the case of the client map.
* The inflight messages are never modified by reference once set, so it is reasonable and more cost effective to copy the whole value.
* The clients are passed by reference, and have more sophisticated locking mechanisms and isolation.
Profiling the solution before and after show a small …
> Fix concurrent map access for clients and inflights causes data race 

- server/internal/circ/writer.go
> Instead of waiting for the writing buffer to have enough space, skip writing and return an error

- hooks.go
- server.go
- Converts second OnPublish hook to OnPublished, and adds an additional OnPublished when returning from qos=0 publishes, as per #118 
- Adjusts Fanpool default values to be slightly more performant, as per #117
- Updates version number
> Fix mis-typed onpublished hook, update version, fanpool defaults

- clients.go
- clients_test.go
- server.go
- server_test.go
Previously, we were enforcing client maximum packet size, but not server set maximum packet size, as per #120 . This PR ensures we reject oversize packets with a 0x95 disconnect. Also fixes minor test issues.
> Enforce server max packet

- server.go
- server_test.go
Add the OnUnsubscribed hook to the unsubscribeClient method，and change the unsubscribeClient to externally visible. In a clustered environment, if a client is disconnected and then connected to another node, the subscriptions on the previous node need to be cleared.
> Add the OnUnsubscribed hook to the unsubscribeClient method

- server.go
- server_test.go
The variable existed can be changed repeatedly within a for loop. An array variable must be used to record the subscription of each filter.
> Variable existed in the method processSubscribe is unstable

- README.md
- clients.go
- clients_test.go
- hooks.go
- hooks/storage/badger/badger.go
- hooks/storage/badger/badger_test.go
- hooks/storage/bolt/bolt.go
- hooks/storage/bolt/bolt_test.go
- hooks/storage/redis/redis.go
- hooks/storage/redis/redis_test.go
- hooks_test.go
- server.go
As per #125, the implementation of the OnExpireInflights hook was inefficient, and fetched all stored inflights and iterated the result, deleting those which had expired. As expired inflight messages equate to dropped inflight inflight messages, the OnExpireInflights hook has been removed, and OnQosDropped(client, pk packets.Packet) is used in it's place. client.ClearInflights is modified to return the packet ids of the inflight messages which were deleted.
> Optimize inflight expiry

- clients.go
- examples/paho.testing/main.go
As per #126, the current implementation of RequestResponseInfo applies to all packets following a connect. This is due to a misinterpretation of the specification. The MQTT v5 specification indicates that the Connect property RequestResponseInfo should only refer to the Connack response properties. This PR adjusted the logic for AllowResponseInfo to ensure it only applies to Connack packets if byte is 0x1, if Compatibilities.AlwaysReturnResponseInfo is set, or the packet is any other type.
Additionally, it removes the usage of Compatibilities.AlwaysReturnResponseInfo in examples/paho/main.go.
> Connect ReturnResponseInfo only applies to Connack values

- packets/codes.go
- packets/tpackets.go
- server.go
- Resolves an issue where MQTTv5 Connack Reason codes were being returned to MQTTv3 clients.
> Use correct connack return codes for MQTTv3

- packets/tpackets.go
- server.go
- server_test.go
- [Optimise Capabilities struct alignment](https://github.com/mochi-co/mqtt/commit/b6a41fc5f6e8da9f1f7dbbc3bbdf48a747ed24ad)
- [Only use RetainAsPublished for v5 clients](https://github.com/mochi-co/mqtt/commit/a1d8ad93269ef778199ae148a220efe498fc6535), per #141
> Ignore retain as published v3

- hooks.go
- hooks_test.go
As per discussion in #145, converts RWMutex protection of Hooks slice to use atomic.Value instead.
cc @thedevop - please check and review 🙇🏻
> Use Atomic instead of RWMutex for Hooks concurrency

- examples/persistence/bolt/main.go
- server.go
examples/persistence/bolt/main.go: invalid config type provided
> invalid config type provided

- listeners/net.go
- listeners/net_test.go
This MR includes the ability to serve incoming connection on an existing `net.Listener`.
resolves #154.
> Include a listener accepting an existing net.Listener

- clients.go
As per #156, the refreshDeadline call has been moved so that it only extends the client deadline if packet transmission was successful. Previous the deadline would be extended even if the client was disconnected.
> Move refreshDeadline to only trigger on successful transmission

- clients.go
- examples/debug/main.go
- inflight.go
- inflight_test.go
- server.go
Take and Return are not super clear method prefixes for the Increase and Decrease quota methods, so they are renamed to Increase and Decrease quota.
> Rename Quota methods for clarity

- server.go
The s.hooks.OnQosPublish method needs to be called, otherwise the following s.hooks.OnQosComplete or processPuback(s.hooks.OnQosComplete) method will report a data not found error.
> failed to delete inflight data

- packets/packets.go
- packets/packets_test.go
- server.go
- server_test.go
After an investigation into the issues seen in #153, the cause is determined to be a misreading of the specification regarding the issuance of retained messages on session takeover, confirmed in this comment by Andy Stanford-Clark https://groups.google.com/g/mqtt/c/ZUpadJna_tA
As such, we will no longer issue retained messages when a session takeover occurs. QoS Inflight queueing continues to behave as expected.
> No longer issue retained messages on session takeover

- clients.go
- clients_test.go
- packets/codec_test.go
- packets/packets.go
- server.go
- server_test.go
Fixes potential endless loop scenario with clients.NextPacketID and updates related tests to cover this scenario.
cc @thedevop Thank you for your code sample - it really helped illustrate the issue!
> Fix potential NextPacketID endless loop, expand tests

- hooks/storage/storage_test.go
- server.go
- system/system.go
- system/system_test.go
- PublishDropped renamed to MessagesDropped for alignment with MessagesSent and MessagesReceived, which refer only to publish packets.
- Exposes the PublishDropped statistic via $SYS topics per #167 on `$SYS/broker/messages/dropped`
cc @thedevop - FAO, above name change! Thank you
> Expose dropped publish messages count in sys info

- packets/packets.go
- packets/properties.go
- packets/properties_test.go
* Changed func `(packets.Properties).Decode` to return the total count of Properties bytes
_including_ VBI header bytes.
* Updated all invocations of `(packets.Properties).Decode` to use the changed return value directly.
* Updated func `TestDecodeProperties` to check the changed return value
> Fixes #171

- clients.go
- server.go
- server_test.go
This is the minimum change needed to use *packets.Packet for outbound chan. I do suggest more use of point to packets.Packet for internal calls, as it will result in less copy/memory allocation, for example cl.WritePacket. Fix #175.
> Use *packets.Packet for outbound chan

- clients.go
- inflight.go
- inflight_test.go
- packets/tpackets.go
- server.go
- server_test.go
An issue was highlighted in which the subscriptions for a client which has undertaken a session takeover could be cleared erroneously in #173.
This behaviour was caused by the orphaned client unsubscribing from the client's topics after the new client had already inherited the subscriptions and begun reading.
Additionally, I identified a secondary, more significant issue in which an expiring orphaned client would delete the existing client from the server client map.
This PR attempts to resolve this issue through three mechanisms:
1. By adding a new `isTakenOver` atomic bit switch to the client which is set to 1 when the client session is inherited by a new client and the client is orphaned (the pointer to the client has been, or shortly will be overwritten in the server client map).
2. …
> Correctly identify and clean taken-over sessions

- packets/packets.go
- packets/tpackets.go
- server_test.go
As indicated in #178, Connect packets containing a username flag and a correctly formed LSB+MSB of [0, 0], but no username bytes were returning an invalid client identifier error. 
The logic for triggering ErrProtocolViolationFlagNoUsername has been moved out of ConnectValidate where it was being called incorrectly, and instead is triggered in ConnectDecode if a username is expected but the buffer has been exhausted.
> Allow 0 byte usernames if correctly formed

- clients.go
- clients_test.go
- server.go
- server_test.go
Addresses #189 by making the client bufio.Reader and bufio.Writer sizes configurable as server options.
The new default value for the reader and writer buffers is 2048. Different values can be configured as such:
```go
server := mqtt.New(&mqtt.Options{
ClientNetWriteBufferSize: 1024,
ClientNetReadBufferSize: 1024,
})
```
> Configurable client bufio reader/writer sizes

- server.go
Simplify the code for the loadInflight and loadRetained methods. Adjust the validation order of the processSubscribe method to ensure that it fails quickly if there is an error, since s.hooks. OnACLCheck generally takes a long time.
> Simplified code

- hooks/storage/badger/badger.go
- hooks/storage/badger/badger_test.go
- hooks/storage/bolt/bolt.go
- hooks/storage/bolt/bolt_test.go
- hooks/storage/redis/redis.go
- hooks/storage/redis/redis_test.go
storage hook should not execute the relevant code if the client has been reconnected.
> #78 storage hook should not execute the relevant code if the client has been reconnected

- .github/workflows/build.yml
I noticed there were warning messages in the GitHub Actions when building the project. This pull request uses the latest version of GitHub Actions and incorporates goveralls.
> Using the latest version of GitHub Actions and incorporates goveralls.

- packets/packets.go
- packets/properties.go
- packets/properties_test.go
As noted in #206, WillProperties are currently validated based on the type of the encompassing packet. While the original issue refers to PayloadFormatIndicator, this also includes any Properties specified in https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901027 for Will Properties.
This PR alters the parameters provided to the Properties.Encode and Decode methods to allow passing of a new WillProperties "packet type" (byte 99) in order to indicate the real context of the properties.
> Correctly validate WillProperties

- clients.go
Adds a lock to client writes to ensure writes are concurrency safe, per  #196
> Add lock to client writes

- clients.go
Makes a small change to refactor the lock introduced in #212 to also lock when the outbound channel is closed, to prevent concurrency issues when trying to write to a channel which has already been closed (per #202)
> Lock on close outbound

- server.go
If SessionExpiryInterval was not set in CONNECT, SessionExpiryIntervalFlag is also not set. According to spec:
```If the Session Expiry Interval is absent the value 0 is used. If it is set to 0, or is absent, the Session ends when the Network Connection is closed.```
> Expire session if SessionExpiryInterval is 0

- clients.go
- clients_test.go
- server.go
- server_test.go
Continuing #202, this PR replaces the client.State.done atomic int with a context value.
> Use context to signal client open state

- README.md
- clients.go
Optimization for use of lock in:
- #212 
- #196
> Minimize client lock duration

- server.go
- server_test.go
As mentioned in both #153 and #233 the retain header was useless as no downstream code utilized it. This issue was duplicated using MQTTX for both LWT and LWT with a DelayInterval.  s.retainMessage is only ever called while processing a Publish packet and thusly is not calling during the processing of the LWT.
> Add retainMessage to LWT to properly handle message retention

- examples/hooks/main.go
- examples/paho.testing/main.go
- hooks.go
- hooks_test.go
- server.go
- server_test.go
Exposes the `func (s *Server) SendConnack(cl *Client, reason packets.Code, present bool, properties *packets.Properties) error` method to allow developers to properly formed SendConnack packets directly. Adds a `err` return value to `OnConnect` allowing developers to halt the connection process.
> Expose SendConnack, err return on OnConnect

- listeners/http_healthcheck.go
- listeners/http_healthcheck_test.go
This commit adds an HTTP healthcheck listener. This is done to allow the broker to comply with certain requirements by cloud providers for certain scaling and container monitoring if required by the provider. For example, [GCP External Passthrough Network Load Balancer](https://cloud.google.com/load-balancing/docs/network)
> Add healthcheck listener

- clients.go
The WriterSize parameter is incorrectly set in the newClient method.
> WriterSize parameter is incorrectly set

- server.go
- server_test.go
If subscriber QoS is less than the publisher QoS, downgrade delivery QoS for that subscriber.
In addition, the below code can be removed, as the during the subscription, we already check if it exceed MaxmumQos:
```go
if out.FixedHeader.Qos > s.Options.Capabilities.MaximumQos {
out.FixedHeader.Qos = s.Options.Capabilities.MaximumQos // [MQTT-3.2.2-9]
}
```
> Ensure msg doesn't exceed subscription QoS

- listeners/websocket.go
- listeners/websocket_test.go
Fixes https://github.com/mochi-co/mqtt/issues/259
> Fix websocket reads for packets > 1 buffer size

- packets/packets.go
- server.go
- server_test.go
Per @bkupidura's note in #251, the retain flag was incorrectly being transmitted as set to MQTTv3 clients. For MQTTv3, the retain flag should be delivered as 'false' after being stored.
This PR adds a correction to this behaviour, and adjusts any tests implementing v3 retain accordingly
cc @bkupidura @thedevop @dgduncan @wind-c - if anyone wishes to review :)
> Retain flag should be delivered as false in v3

- server.go
- server_test.go
Following #255, I noticed that `s.Options.Capabilities.RetainAvailable` is advisory only - it only indicates to the client that retain is unavailable, but does not actually disable the feature. This PR prevents messages from being retained if `s.Options.Capabilities.RetainAvailable = 0`.
> Do not retain messages if retain is not available

- server.go
When calling the OnUnsubscribed method during secondary development, the corresponding processor will be selected based on the type of the packet. However, the lack of packet type in UnsubscribeClient results in the inability to select the appropriate processor successfully.
> method UnsubscribeClient's packet add fixedHeader

- examples/paho.testing/main.go
- packets/codes.go
- packets/packets.go
- packets/tpackets.go
- server.go
- server_test.go
Following a discussion in #249, it became apparent that we do not currently return packet errors in acks when a received publish packet is invalid (or an error has been returned by the OnPublish hook), which is a behaviour indicated in the MQTT v5 specification. 
This PR adds a check statement to return an error ack if the client is v5, the error is a packet error (not a 'true error'), and the Qos > 0. 
Additionally, a line has been corrected allowing the User Properties to be propagated to the ack, as per the spec (formerly this would be dropped). As such, a compatibility mode has been added to bypass a spec violation in the paho interoperability library which expects no user properties. We should consider migrating away from the paho testing library.
Otherwise passing Paho and Unit …
> Allow Publish to return custom Ack error responses

- listeners/listeners.go
- server.go
Following #298 and #299, this PR presents a small solution to track the connection alive status of every client by repurposing the Listeners waitgroup to track clients instead of listeners. This change ensures that the Hooks shutdown sequence cannot be completed until all clients have successfully and sequentially exited their goroutines (between cl.Read and OnDisconnect). In this way, we can leverage the existing shutdown signally code.
Tests are unaffected, Paho passing.
> Refactor Listener WG to track clients

- clients.go
- clients_test.go
- server.go
Following #293 and #296, this PR adds a warning if the client connecting has a keepalive set and the keepalive is below a minimum recommended keepalive value.
> Emit warning if client keepalive is less than recommended minimum

- clients.go
- server_test.go
This code snippet can improve the network throughput for the subscriber.
> improve transport performance with bufio

- server.go
- server_test.go
I encountered a problem similar to #339 . If the broker is forcefully shut down, and clients have the clean flag set, after restarting the broker and calling loadClients(), these expired clients will be retained indefinitely if the client is no longer connected.
It is necessary to handle expired clients in server.loadClients(). Call OnDisconnect() to trigger the hook for clearing persistent clients. Also, if a client has expired, there is no need to retain this client in server.Clients.
> Handle expired clients in server.loadClients().

- clients.go
Ensure write buffer is not the one used by Hook. As reported in #346.
> Fix data race issue with write buffer

- listeners/tcp.go
* This is the more accurate and correct address of the listener
* Useful if you want to listen on port 0 to dynamically create listeners (think of unit/integration tests)
> feat: return tcp.Address from listener, if exists

- README-CN.md
- server.go
In the server.loadClients() and when using inlineClient, NewClient() is called, but these may not necessarily represent actual connections. Calling go cl.WriteLoop() within NewClient() leads to a goroutine leak. I think moving go cl.WriteLoop() out of NewClient() and placing it in either server.EstablishConnection() or server.attachClient() would be more reasonable.
> Move cl.WriteLoop() to attachClient() and call cl.Stop() in loadClients() to update client.State.

- clients.go
- packets/packets.go
- packets/properties.go
Few buffer optimizations:
1. Avoid creating/writing to outbound buffer if outbound was nil and pkt is larger than ClientNetWriteBufferSize
2. Use mempool for Properties Encode as well
3. Use the more efficient Write instead of WriteTo for Buffer to Buffer writes (as it won't be partially successful)
Benchmark comparing Write vs WriteTo (the performance difference is reverse proportion to the packet size, using 128 bytes for benchmark as vast majority packets without payload should be less than that):
```go
func BenchmarkWrite(b *testing.B) {
const PacketSize = 128
d := make([]byte, PacketSize)
if _, err := rand.Read(d); err != nil {
panic(err)
}
dst := new(bytes.Buffer)
b.ResetTimer()
b.ReportAllocs()
for i := 0; i < b.N; i++ {
src := bytes.NewBuffer(d)
dst.Write(src.Bytes())
dst.Reset() …
```
> Buffer optimizations

- server.go
- server_test.go
> Only pass a copy of system.Info to hooks

- clients.go
- clients_test.go
- server.go
- server_test.go
> Allow configurable max stored qos > 0 messages

- examples/persistence/badger/main.go
- hooks/storage/badger/badger.go
- hooks/storage/badger/badger_test.go
For issues #370, #369, and #363. I've tested it myself under the condition of setting the log file size to 1MB. With 1000 clients repeatedly connecting and disconnecting with the same client ID, if GC is not enabled, the log file continues to grow indefinitely. Enabling the GC loop resolves this issue.
> Add BadgerDB garbage collection.

- config/config.go
- config/config_test.go
- examples/config/config.yaml
- server.go
- server_test.go
Adds the ability to configure logging level from the file based config. It does this by creating a logger with a `Levelvar` during file based configuration and parsing the included. If no `logging` options are configured, `INFO` is assumed.
> Add logging level file config

- clients.go
- clients_test.go
- server.go
My persistence hook needs to know what time a client disconnected. The field `Client.State.disconnected` has that information but it's not exposed in the API, so I added a simple public accessor method `Client.StopTime()`.
> Added client.StopTime(), to expose `disconnected`

- hooks/storage/storage.go
- hooks/storage/storage_test.go
Adding `omitempty` to the JSON metadata of the `storage` struct fields significantly cuts down the size of the marshaled JSON when a hook is persisting state to a database.
I've left it out on fields that, in my experience, never have the default value; but if you feel it should be consistent on all fields, I can add it to the rest.
> Added `omitempty` to storage structs

- server.go
Fix https://github.com/mochi-mqtt/server/issues/416
The reason I want to open this PR:
* cl.ID is set from the `pk.Connect.ClientIdentifier` in [clients.go](https://github.com/mochi-mqtt/server/blob/82c96fa4e3f20259c2d947bb87eb8dc885ef6824/clients.go#L236-L236), It also is the same value as the assignedClientId if there is one. Therefore it is more correct, but also for the reasons below:
* This allows my custom implementation to rely on `cl.ID` and override it and the assigned id returned to the client(I assign intentional, known, client ids to specific clients. We want to control the client ids based on the authenticating client.) 
All tests still pass, including the existing client takeover tests.
@mochi-co  Do you think the existing tests are good for this, or do we want some kind of …
> use cl.ID instead of pk.Connect.ClientIdentifier when looking for existing clients in inheritClientSession

- hooks/storage/badger/badger.go
- hooks/storage/bolt/bolt.go
- hooks/storage/pebble/pebble.go
- hooks/storage/redis/redis.go
- hooks/storage/storage.go
- server.go
- server_test.go
Resolved an issue where persisted QoS 1 messages were not correctly loaded into the appropriate client instance during server startup.
> Fix QoS 1 message delivery after server restart

- cmd/main.go
- examples/tls/main.go
> feat: Add TLS Cert File flag

- clients.go
- server.go
- server_test.go
This includes changes:
1. Address @dariopb's issue in #442 
2. Only set pk.Expiry if pk.Properties.MessageExpiryInterval or MaximumMessageExpiryInterval is not zero-value
3. Ensure outgoing pk.Properties.MessageExpiryInterval doesn't contain uint32(of negative value or zero-value) by setting a minimum of 1
> Improve message expiry
